name: .NET Core

on:
  push:
    branches: [ master ]
    
jobs:
  Deploy:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x
        cache: true
         
    - name: DotNet Restore
      run: dotnet restore --locked-mode
    
    - name: DotNet Publish
      run: dotnet publish ./WebHook/WebHook.csproj -c Release -r linux-x64 -p:PublishReadyToRun=true --self-contained false
      
    - name: Stop ScheduleBot Service
      uses: garygrossgarten/github-action-ssh@release
      with:
        command: systemctl stop ScheduleBot
        host: ${{ secrets.REMOTE_HOST }}
        port: 10022
        username: ${{ secrets.REMOTE_USER }}
        passphrase: ${{ secrets.PASSPHRASE }}
        privateKey: ${{ secrets.REMOTE_SSH_KEY }}
      
    - name: Copy to Server via SCP
      uses: appleboy/scp-action@v0.1.7
      with:
        host: ${{ secrets.REMOTE_HOST }}
        port: 10022
        username: ${{ secrets.REMOTE_USER }}
        key: ${{ secrets.REMOTE_SSH_KEY }}
        passphrase: ${{ secrets.PASSPHRASE }}
        source: /home/runner/work/TulsuScheduleBot/TulsuScheduleBot/WebHook/bin/Release/net8.0/linux-x64/publish/*
        target: ${{ secrets.REMOTE_TARGET }}
        rm: true
      
    - name: Start ScheduleBot Service
      uses: garygrossgarten/github-action-ssh@release
      with:
        command: systemctl start ScheduleBot
        host: ${{ secrets.REMOTE_HOST }}
        port: 10022
        username: ${{ secrets.REMOTE_USER }}
        passphrase: ${{ secrets.PASSPHRASE }}
        privateKey: ${{ secrets.REMOTE_SSH_KEY }}

    - name: Get Last Commit Info
      id: get_commit
      run: |
        echo "LAST_COMMIT_MESSAGE=$(git log -1 --pretty=format:'%s')" >> $GITHUB_ENV
        echo "LAST_COMMIT_AUTHOR=$(git log -1 --pretty=format:'%an')" >> $GITHUB_ENV
        echo "LAST_COMMIT_HASH=$(git log -1 --pretty=format:'%H')" >> $GITHUB_ENV

    - name: Send Telegram Notification
      env:
        TELEGRAM_TOKEN: ${{ secrets.TELEGRAM_TOKEN }}
        CHAT_ID: ${{ secrets.CHAT_ID }}
        LAST_COMMIT_MESSAGE: ${{ env.LAST_COMMIT_MESSAGE }}
        LAST_COMMIT_AUTHOR: ${{ env.LAST_COMMIT_AUTHOR }}
        LAST_COMMIT_HASH: ${{ env.LAST_COMMIT_HASH }}
        GITHUB_REPOSITORY: ${{ github.repository }}
      run: |
        REPO_URL="https://github.com/${GITHUB_REPOSITORY}"
        COMMIT_URL="${REPO_URL}/commit/${LAST_COMMIT_HASH}"
        curl -s -X POST https://api.telegram.org/bot${TELEGRAM_TOKEN}/sendMessage \
        -d chat_id=${CHAT_ID} \
        -d parse_mode="MarkdownV2" \
        -d disable_web_page_preview=true \
        -d text="*New commit in [${GITHUB_REPOSITORY}](${REPO_URL})*%0A%0A*Author:* ${LAST_COMMIT_AUTHOR}%0A[View Commit](${COMMIT_URL})"
